# Generated by Django 4.2.3 on 2023-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Company', 'Company'), ('Store Owner', 'Store Owner'), ('Store Manager', 'Store Manager')], default=('Store Owner', 'Store Owner'), max_length=150),
        ),
    ]
