# Generated by Django 4.2.5 on 2023-09-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_producer_delete_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store_Owner',
            new_name='StoreOwner',
        ),
    ]
