# Generated by Django 4.2.3 on 2023-09-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_producer_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('quantity', models.IntegerField()),
                ('measure_type', models.CharField(choices=[('Piece', 'Piece'), ('Liter', 'Liter'), ('Kilogram', 'Kilogram'), ('Meter', 'Meter')], max_length=100)),
                ('price', models.IntegerField()),
                ('produced_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('confirm_date', models.DateTimeField(default=None)),
                ('receiving_date', models.DateTimeField(default=None)),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('In the way', 'In the way'), ('Preparing for delivery', 'Preparing for delivery'), ('Searching', 'Searching')], max_length=100)),
                ('receiver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='account.user')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_orders', to='account.producer')),
            ],
        ),
    ]
