# Generated by Django 4.2.5 on 2023-09-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_receiver_alter_order_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirm_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiving_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
